//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support.SorenaSms {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SorenaSms.sornaserviceSoap")]
    public interface sornaserviceSoap {
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getsystemcredit", ReplyAction="*")]
        Support.SorenaSms.getsystemcreditResponse getsystemcredit(Support.SorenaSms.getsystemcreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getsystemcredit", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.getsystemcreditResponse> getsystemcreditAsync(Support.SorenaSms.getsystemcreditRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSMSEngine", ReplyAction="*")]
        Support.SorenaSms.MultiSMSEngineResponse MultiSMSEngine(Support.SorenaSms.MultiSMSEngineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSMSEngine", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineResponse> MultiSMSEngineAsync(Support.SorenaSms.MultiSMSEngineRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSMSEngineBlackList", ReplyAction="*")]
        Support.SorenaSms.MultiSMSEngineBlackListResponse MultiSMSEngineBlackList(Support.SorenaSms.MultiSMSEngineBlackListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSMSEngineBlackList", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineBlackListResponse> MultiSMSEngineBlackListAsync(Support.SorenaSms.MultiSMSEngineBlackListRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSMSEngineshatel", ReplyAction="*")]
        Support.SorenaSms.MultiSMSEngineshatelResponse MultiSMSEngineshatel(Support.SorenaSms.MultiSMSEngineshatelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSMSEngineshatel", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineshatelResponse> MultiSMSEngineshatelAsync(Support.SorenaSms.MultiSMSEngineshatelRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSMSEngine021", ReplyAction="*")]
        Support.SorenaSms.MultiSMSEngine021Response MultiSMSEngine021(Support.SorenaSms.MultiSMSEngine021Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MultiSMSEngine021", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngine021Response> MultiSMSEngine021Async(Support.SorenaSms.MultiSMSEngine021Request request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatusSMSEngine", ReplyAction="*")]
        Support.SorenaSms.GetStatusSMSEngineResponse GetStatusSMSEngine(Support.SorenaSms.GetStatusSMSEngineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStatusSMSEngine", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.GetStatusSMSEngineResponse> GetStatusSMSEngineAsync(Support.SorenaSms.GetStatusSMSEngineRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleSMSEngineShatel", ReplyAction="*")]
        Support.SorenaSms.SingleSMSEngineShatelResponse SingleSMSEngineShatel(Support.SorenaSms.SingleSMSEngineShatelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleSMSEngineShatel", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineShatelResponse> SingleSMSEngineShatelAsync(Support.SorenaSms.SingleSMSEngineShatelRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleSMSEngine", ReplyAction="*")]
        Support.SorenaSms.SingleSMSEngineResponse SingleSMSEngine(Support.SorenaSms.SingleSMSEngineRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleSMSEngine", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineResponse> SingleSMSEngineAsync(Support.SorenaSms.SingleSMSEngineRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleSMSEngineBlacklist", ReplyAction="*")]
        Support.SorenaSms.SingleSMSEngineBlacklistResponse SingleSMSEngineBlacklist(Support.SorenaSms.SingleSMSEngineBlacklistRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleSMSEngineBlacklist", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineBlacklistResponse> SingleSMSEngineBlacklistAsync(Support.SorenaSms.SingleSMSEngineBlacklistRequest request);
        
        // CODEGEN: Generating message contract since element name UserName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleSMSEngine021", ReplyAction="*")]
        Support.SorenaSms.SingleSMSEngine021Response SingleSMSEngine021(Support.SorenaSms.SingleSMSEngine021Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleSMSEngine021", ReplyAction="*")]
        System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngine021Response> SingleSMSEngine021Async(Support.SorenaSms.SingleSMSEngine021Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsystemcreditRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getsystemcredit", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.getsystemcreditRequestBody Body;
        
        public getsystemcreditRequest() {
        }
        
        public getsystemcreditRequest(Support.SorenaSms.getsystemcreditRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getsystemcreditRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        public getsystemcreditRequestBody() {
        }
        
        public getsystemcreditRequestBody(int PortalCode, string UserName, string PassWord) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getsystemcreditResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getsystemcreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.getsystemcreditResponseBody Body;
        
        public getsystemcreditResponse() {
        }
        
        public getsystemcreditResponse(Support.SorenaSms.getsystemcreditResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getsystemcreditResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double getsystemcreditResult;
        
        public getsystemcreditResponseBody() {
        }
        
        public getsystemcreditResponseBody(double getsystemcreditResult) {
            this.getsystemcreditResult = getsystemcreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSMSEngineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSMSEngine", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.MultiSMSEngineRequestBody Body;
        
        public MultiSMSEngineRequest() {
        }
        
        public MultiSMSEngineRequest(Support.SorenaSms.MultiSMSEngineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSMSEngineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Support.SorenaSms.ArrayOfString Mobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Support.SorenaSms.ArrayOfString Messages;
        
        public MultiSMSEngineRequestBody() {
        }
        
        public MultiSMSEngineRequestBody(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.Mobiles = Mobiles;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSMSEngineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSMSEngineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.MultiSMSEngineResponseBody Body;
        
        public MultiSMSEngineResponse() {
        }
        
        public MultiSMSEngineResponse(Support.SorenaSms.MultiSMSEngineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSMSEngineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Support.SorenaSms.ArrayOfString MultiSMSEngineResult;
        
        public MultiSMSEngineResponseBody() {
        }
        
        public MultiSMSEngineResponseBody(Support.SorenaSms.ArrayOfString MultiSMSEngineResult) {
            this.MultiSMSEngineResult = MultiSMSEngineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSMSEngineBlackListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSMSEngineBlackList", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.MultiSMSEngineBlackListRequestBody Body;
        
        public MultiSMSEngineBlackListRequest() {
        }
        
        public MultiSMSEngineBlackListRequest(Support.SorenaSms.MultiSMSEngineBlackListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSMSEngineBlackListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Support.SorenaSms.ArrayOfString Mobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Support.SorenaSms.ArrayOfString Messages;
        
        public MultiSMSEngineBlackListRequestBody() {
        }
        
        public MultiSMSEngineBlackListRequestBody(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.Mobiles = Mobiles;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSMSEngineBlackListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSMSEngineBlackListResponse", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.MultiSMSEngineBlackListResponseBody Body;
        
        public MultiSMSEngineBlackListResponse() {
        }
        
        public MultiSMSEngineBlackListResponse(Support.SorenaSms.MultiSMSEngineBlackListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSMSEngineBlackListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Support.SorenaSms.ArrayOfString MultiSMSEngineBlackListResult;
        
        public MultiSMSEngineBlackListResponseBody() {
        }
        
        public MultiSMSEngineBlackListResponseBody(Support.SorenaSms.ArrayOfString MultiSMSEngineBlackListResult) {
            this.MultiSMSEngineBlackListResult = MultiSMSEngineBlackListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSMSEngineshatelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSMSEngineshatel", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.MultiSMSEngineshatelRequestBody Body;
        
        public MultiSMSEngineshatelRequest() {
        }
        
        public MultiSMSEngineshatelRequest(Support.SorenaSms.MultiSMSEngineshatelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSMSEngineshatelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Support.SorenaSms.ArrayOfString Mobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Support.SorenaSms.ArrayOfString Messages;
        
        public MultiSMSEngineshatelRequestBody() {
        }
        
        public MultiSMSEngineshatelRequestBody(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.Mobiles = Mobiles;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSMSEngineshatelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSMSEngineshatelResponse", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.MultiSMSEngineshatelResponseBody Body;
        
        public MultiSMSEngineshatelResponse() {
        }
        
        public MultiSMSEngineshatelResponse(Support.SorenaSms.MultiSMSEngineshatelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSMSEngineshatelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Support.SorenaSms.ArrayOfString MultiSMSEngineshatelResult;
        
        public MultiSMSEngineshatelResponseBody() {
        }
        
        public MultiSMSEngineshatelResponseBody(Support.SorenaSms.ArrayOfString MultiSMSEngineshatelResult) {
            this.MultiSMSEngineshatelResult = MultiSMSEngineshatelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSMSEngine021Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSMSEngine021", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.MultiSMSEngine021RequestBody Body;
        
        public MultiSMSEngine021Request() {
        }
        
        public MultiSMSEngine021Request(Support.SorenaSms.MultiSMSEngine021RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSMSEngine021RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Support.SorenaSms.ArrayOfString Mobiles;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Support.SorenaSms.ArrayOfString Messages;
        
        public MultiSMSEngine021RequestBody() {
        }
        
        public MultiSMSEngine021RequestBody(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.Mobiles = Mobiles;
            this.Messages = Messages;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MultiSMSEngine021Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MultiSMSEngine021Response", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.MultiSMSEngine021ResponseBody Body;
        
        public MultiSMSEngine021Response() {
        }
        
        public MultiSMSEngine021Response(Support.SorenaSms.MultiSMSEngine021ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class MultiSMSEngine021ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Support.SorenaSms.ArrayOfString MultiSMSEngine021Result;
        
        public MultiSMSEngine021ResponseBody() {
        }
        
        public MultiSMSEngine021ResponseBody(Support.SorenaSms.ArrayOfString MultiSMSEngine021Result) {
            this.MultiSMSEngine021Result = MultiSMSEngine021Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusSMSEngineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusSMSEngine", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.GetStatusSMSEngineRequestBody Body;
        
        public GetStatusSMSEngineRequest() {
        }
        
        public GetStatusSMSEngineRequest(Support.SorenaSms.GetStatusSMSEngineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusSMSEngineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ReferenceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string state_sms;
        
        public GetStatusSMSEngineRequestBody() {
        }
        
        public GetStatusSMSEngineRequestBody(int PortalCode, string UserName, string PassWord, string ReferenceCode, string state_sms) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.ReferenceCode = ReferenceCode;
            this.state_sms = state_sms;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusSMSEngineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusSMSEngineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.GetStatusSMSEngineResponseBody Body;
        
        public GetStatusSMSEngineResponse() {
        }
        
        public GetStatusSMSEngineResponse(Support.SorenaSms.GetStatusSMSEngineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatusSMSEngineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStatusSMSEngineResult;
        
        public GetStatusSMSEngineResponseBody() {
        }
        
        public GetStatusSMSEngineResponseBody(string GetStatusSMSEngineResult) {
            this.GetStatusSMSEngineResult = GetStatusSMSEngineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleSMSEngineShatelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleSMSEngineShatel", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.SingleSMSEngineShatelRequestBody Body;
        
        public SingleSMSEngineShatelRequest() {
        }
        
        public SingleSMSEngineShatelRequest(Support.SorenaSms.SingleSMSEngineShatelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleSMSEngineShatelRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        public SingleSMSEngineShatelRequestBody() {
        }
        
        public SingleSMSEngineShatelRequestBody(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.Mobile = Mobile;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleSMSEngineShatelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleSMSEngineShatelResponse", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.SingleSMSEngineShatelResponseBody Body;
        
        public SingleSMSEngineShatelResponse() {
        }
        
        public SingleSMSEngineShatelResponse(Support.SorenaSms.SingleSMSEngineShatelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleSMSEngineShatelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SingleSMSEngineShatelResult;
        
        public SingleSMSEngineShatelResponseBody() {
        }
        
        public SingleSMSEngineShatelResponseBody(string SingleSMSEngineShatelResult) {
            this.SingleSMSEngineShatelResult = SingleSMSEngineShatelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleSMSEngineRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleSMSEngine", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.SingleSMSEngineRequestBody Body;
        
        public SingleSMSEngineRequest() {
        }
        
        public SingleSMSEngineRequest(Support.SorenaSms.SingleSMSEngineRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleSMSEngineRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        public SingleSMSEngineRequestBody() {
        }
        
        public SingleSMSEngineRequestBody(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.Mobile = Mobile;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleSMSEngineResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleSMSEngineResponse", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.SingleSMSEngineResponseBody Body;
        
        public SingleSMSEngineResponse() {
        }
        
        public SingleSMSEngineResponse(Support.SorenaSms.SingleSMSEngineResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleSMSEngineResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SingleSMSEngineResult;
        
        public SingleSMSEngineResponseBody() {
        }
        
        public SingleSMSEngineResponseBody(string SingleSMSEngineResult) {
            this.SingleSMSEngineResult = SingleSMSEngineResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleSMSEngineBlacklistRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleSMSEngineBlacklist", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.SingleSMSEngineBlacklistRequestBody Body;
        
        public SingleSMSEngineBlacklistRequest() {
        }
        
        public SingleSMSEngineBlacklistRequest(Support.SorenaSms.SingleSMSEngineBlacklistRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleSMSEngineBlacklistRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        public SingleSMSEngineBlacklistRequestBody() {
        }
        
        public SingleSMSEngineBlacklistRequestBody(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.Mobile = Mobile;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleSMSEngineBlacklistResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleSMSEngineBlacklistResponse", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.SingleSMSEngineBlacklistResponseBody Body;
        
        public SingleSMSEngineBlacklistResponse() {
        }
        
        public SingleSMSEngineBlacklistResponse(Support.SorenaSms.SingleSMSEngineBlacklistResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleSMSEngineBlacklistResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SingleSMSEngineBlacklistResult;
        
        public SingleSMSEngineBlacklistResponseBody() {
        }
        
        public SingleSMSEngineBlacklistResponseBody(string SingleSMSEngineBlacklistResult) {
            this.SingleSMSEngineBlacklistResult = SingleSMSEngineBlacklistResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleSMSEngine021Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleSMSEngine021", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.SingleSMSEngine021RequestBody Body;
        
        public SingleSMSEngine021Request() {
        }
        
        public SingleSMSEngine021Request(Support.SorenaSms.SingleSMSEngine021RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleSMSEngine021RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int PortalCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string UserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PassWord;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Mobile;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Message;
        
        public SingleSMSEngine021RequestBody() {
        }
        
        public SingleSMSEngine021RequestBody(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            this.PortalCode = PortalCode;
            this.UserName = UserName;
            this.PassWord = PassWord;
            this.Mobile = Mobile;
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SingleSMSEngine021Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SingleSMSEngine021Response", Namespace="http://tempuri.org/", Order=0)]
        public Support.SorenaSms.SingleSMSEngine021ResponseBody Body;
        
        public SingleSMSEngine021Response() {
        }
        
        public SingleSMSEngine021Response(Support.SorenaSms.SingleSMSEngine021ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleSMSEngine021ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SingleSMSEngine021Result;
        
        public SingleSMSEngine021ResponseBody() {
        }
        
        public SingleSMSEngine021ResponseBody(string SingleSMSEngine021Result) {
            this.SingleSMSEngine021Result = SingleSMSEngine021Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sornaserviceSoapChannel : Support.SorenaSms.sornaserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sornaserviceSoapClient : System.ServiceModel.ClientBase<Support.SorenaSms.sornaserviceSoap>, Support.SorenaSms.sornaserviceSoap {
        
        public sornaserviceSoapClient() {
        }
        
        public sornaserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sornaserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sornaserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sornaserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.getsystemcreditResponse Support.SorenaSms.sornaserviceSoap.getsystemcredit(Support.SorenaSms.getsystemcreditRequest request) {
            return base.Channel.getsystemcredit(request);
        }
        
        public double getsystemcredit(int PortalCode, string UserName, string PassWord) {
            Support.SorenaSms.getsystemcreditRequest inValue = new Support.SorenaSms.getsystemcreditRequest();
            inValue.Body = new Support.SorenaSms.getsystemcreditRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            Support.SorenaSms.getsystemcreditResponse retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).getsystemcredit(inValue);
            return retVal.Body.getsystemcreditResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.getsystemcreditResponse> Support.SorenaSms.sornaserviceSoap.getsystemcreditAsync(Support.SorenaSms.getsystemcreditRequest request) {
            return base.Channel.getsystemcreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.getsystemcreditResponse> getsystemcreditAsync(int PortalCode, string UserName, string PassWord) {
            Support.SorenaSms.getsystemcreditRequest inValue = new Support.SorenaSms.getsystemcreditRequest();
            inValue.Body = new Support.SorenaSms.getsystemcreditRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).getsystemcreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.MultiSMSEngineResponse Support.SorenaSms.sornaserviceSoap.MultiSMSEngine(Support.SorenaSms.MultiSMSEngineRequest request) {
            return base.Channel.MultiSMSEngine(request);
        }
        
        public Support.SorenaSms.ArrayOfString MultiSMSEngine(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            Support.SorenaSms.MultiSMSEngineRequest inValue = new Support.SorenaSms.MultiSMSEngineRequest();
            inValue.Body = new Support.SorenaSms.MultiSMSEngineRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobiles = Mobiles;
            inValue.Body.Messages = Messages;
            Support.SorenaSms.MultiSMSEngineResponse retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).MultiSMSEngine(inValue);
            return retVal.Body.MultiSMSEngineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineResponse> Support.SorenaSms.sornaserviceSoap.MultiSMSEngineAsync(Support.SorenaSms.MultiSMSEngineRequest request) {
            return base.Channel.MultiSMSEngineAsync(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineResponse> MultiSMSEngineAsync(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            Support.SorenaSms.MultiSMSEngineRequest inValue = new Support.SorenaSms.MultiSMSEngineRequest();
            inValue.Body = new Support.SorenaSms.MultiSMSEngineRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobiles = Mobiles;
            inValue.Body.Messages = Messages;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).MultiSMSEngineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.MultiSMSEngineBlackListResponse Support.SorenaSms.sornaserviceSoap.MultiSMSEngineBlackList(Support.SorenaSms.MultiSMSEngineBlackListRequest request) {
            return base.Channel.MultiSMSEngineBlackList(request);
        }
        
        public Support.SorenaSms.ArrayOfString MultiSMSEngineBlackList(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            Support.SorenaSms.MultiSMSEngineBlackListRequest inValue = new Support.SorenaSms.MultiSMSEngineBlackListRequest();
            inValue.Body = new Support.SorenaSms.MultiSMSEngineBlackListRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobiles = Mobiles;
            inValue.Body.Messages = Messages;
            Support.SorenaSms.MultiSMSEngineBlackListResponse retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).MultiSMSEngineBlackList(inValue);
            return retVal.Body.MultiSMSEngineBlackListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineBlackListResponse> Support.SorenaSms.sornaserviceSoap.MultiSMSEngineBlackListAsync(Support.SorenaSms.MultiSMSEngineBlackListRequest request) {
            return base.Channel.MultiSMSEngineBlackListAsync(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineBlackListResponse> MultiSMSEngineBlackListAsync(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            Support.SorenaSms.MultiSMSEngineBlackListRequest inValue = new Support.SorenaSms.MultiSMSEngineBlackListRequest();
            inValue.Body = new Support.SorenaSms.MultiSMSEngineBlackListRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobiles = Mobiles;
            inValue.Body.Messages = Messages;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).MultiSMSEngineBlackListAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.MultiSMSEngineshatelResponse Support.SorenaSms.sornaserviceSoap.MultiSMSEngineshatel(Support.SorenaSms.MultiSMSEngineshatelRequest request) {
            return base.Channel.MultiSMSEngineshatel(request);
        }
        
        public Support.SorenaSms.ArrayOfString MultiSMSEngineshatel(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            Support.SorenaSms.MultiSMSEngineshatelRequest inValue = new Support.SorenaSms.MultiSMSEngineshatelRequest();
            inValue.Body = new Support.SorenaSms.MultiSMSEngineshatelRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobiles = Mobiles;
            inValue.Body.Messages = Messages;
            Support.SorenaSms.MultiSMSEngineshatelResponse retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).MultiSMSEngineshatel(inValue);
            return retVal.Body.MultiSMSEngineshatelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineshatelResponse> Support.SorenaSms.sornaserviceSoap.MultiSMSEngineshatelAsync(Support.SorenaSms.MultiSMSEngineshatelRequest request) {
            return base.Channel.MultiSMSEngineshatelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngineshatelResponse> MultiSMSEngineshatelAsync(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            Support.SorenaSms.MultiSMSEngineshatelRequest inValue = new Support.SorenaSms.MultiSMSEngineshatelRequest();
            inValue.Body = new Support.SorenaSms.MultiSMSEngineshatelRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobiles = Mobiles;
            inValue.Body.Messages = Messages;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).MultiSMSEngineshatelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.MultiSMSEngine021Response Support.SorenaSms.sornaserviceSoap.MultiSMSEngine021(Support.SorenaSms.MultiSMSEngine021Request request) {
            return base.Channel.MultiSMSEngine021(request);
        }
        
        public Support.SorenaSms.ArrayOfString MultiSMSEngine021(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            Support.SorenaSms.MultiSMSEngine021Request inValue = new Support.SorenaSms.MultiSMSEngine021Request();
            inValue.Body = new Support.SorenaSms.MultiSMSEngine021RequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobiles = Mobiles;
            inValue.Body.Messages = Messages;
            Support.SorenaSms.MultiSMSEngine021Response retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).MultiSMSEngine021(inValue);
            return retVal.Body.MultiSMSEngine021Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngine021Response> Support.SorenaSms.sornaserviceSoap.MultiSMSEngine021Async(Support.SorenaSms.MultiSMSEngine021Request request) {
            return base.Channel.MultiSMSEngine021Async(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.MultiSMSEngine021Response> MultiSMSEngine021Async(int PortalCode, string UserName, string PassWord, Support.SorenaSms.ArrayOfString Mobiles, Support.SorenaSms.ArrayOfString Messages) {
            Support.SorenaSms.MultiSMSEngine021Request inValue = new Support.SorenaSms.MultiSMSEngine021Request();
            inValue.Body = new Support.SorenaSms.MultiSMSEngine021RequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobiles = Mobiles;
            inValue.Body.Messages = Messages;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).MultiSMSEngine021Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.GetStatusSMSEngineResponse Support.SorenaSms.sornaserviceSoap.GetStatusSMSEngine(Support.SorenaSms.GetStatusSMSEngineRequest request) {
            return base.Channel.GetStatusSMSEngine(request);
        }
        
        public string GetStatusSMSEngine(int PortalCode, string UserName, string PassWord, string ReferenceCode, string state_sms) {
            Support.SorenaSms.GetStatusSMSEngineRequest inValue = new Support.SorenaSms.GetStatusSMSEngineRequest();
            inValue.Body = new Support.SorenaSms.GetStatusSMSEngineRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.ReferenceCode = ReferenceCode;
            inValue.Body.state_sms = state_sms;
            Support.SorenaSms.GetStatusSMSEngineResponse retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).GetStatusSMSEngine(inValue);
            return retVal.Body.GetStatusSMSEngineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.GetStatusSMSEngineResponse> Support.SorenaSms.sornaserviceSoap.GetStatusSMSEngineAsync(Support.SorenaSms.GetStatusSMSEngineRequest request) {
            return base.Channel.GetStatusSMSEngineAsync(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.GetStatusSMSEngineResponse> GetStatusSMSEngineAsync(int PortalCode, string UserName, string PassWord, string ReferenceCode, string state_sms) {
            Support.SorenaSms.GetStatusSMSEngineRequest inValue = new Support.SorenaSms.GetStatusSMSEngineRequest();
            inValue.Body = new Support.SorenaSms.GetStatusSMSEngineRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.ReferenceCode = ReferenceCode;
            inValue.Body.state_sms = state_sms;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).GetStatusSMSEngineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.SingleSMSEngineShatelResponse Support.SorenaSms.sornaserviceSoap.SingleSMSEngineShatel(Support.SorenaSms.SingleSMSEngineShatelRequest request) {
            return base.Channel.SingleSMSEngineShatel(request);
        }
        
        public string SingleSMSEngineShatel(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            Support.SorenaSms.SingleSMSEngineShatelRequest inValue = new Support.SorenaSms.SingleSMSEngineShatelRequest();
            inValue.Body = new Support.SorenaSms.SingleSMSEngineShatelRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            Support.SorenaSms.SingleSMSEngineShatelResponse retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).SingleSMSEngineShatel(inValue);
            return retVal.Body.SingleSMSEngineShatelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineShatelResponse> Support.SorenaSms.sornaserviceSoap.SingleSMSEngineShatelAsync(Support.SorenaSms.SingleSMSEngineShatelRequest request) {
            return base.Channel.SingleSMSEngineShatelAsync(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineShatelResponse> SingleSMSEngineShatelAsync(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            Support.SorenaSms.SingleSMSEngineShatelRequest inValue = new Support.SorenaSms.SingleSMSEngineShatelRequest();
            inValue.Body = new Support.SorenaSms.SingleSMSEngineShatelRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).SingleSMSEngineShatelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.SingleSMSEngineResponse Support.SorenaSms.sornaserviceSoap.SingleSMSEngine(Support.SorenaSms.SingleSMSEngineRequest request) {
            return base.Channel.SingleSMSEngine(request);
        }
        
        public string SingleSMSEngine(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            Support.SorenaSms.SingleSMSEngineRequest inValue = new Support.SorenaSms.SingleSMSEngineRequest();
            inValue.Body = new Support.SorenaSms.SingleSMSEngineRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            Support.SorenaSms.SingleSMSEngineResponse retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).SingleSMSEngine(inValue);
            return retVal.Body.SingleSMSEngineResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineResponse> Support.SorenaSms.sornaserviceSoap.SingleSMSEngineAsync(Support.SorenaSms.SingleSMSEngineRequest request) {
            return base.Channel.SingleSMSEngineAsync(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineResponse> SingleSMSEngineAsync(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            Support.SorenaSms.SingleSMSEngineRequest inValue = new Support.SorenaSms.SingleSMSEngineRequest();
            inValue.Body = new Support.SorenaSms.SingleSMSEngineRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).SingleSMSEngineAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.SingleSMSEngineBlacklistResponse Support.SorenaSms.sornaserviceSoap.SingleSMSEngineBlacklist(Support.SorenaSms.SingleSMSEngineBlacklistRequest request) {
            return base.Channel.SingleSMSEngineBlacklist(request);
        }
        
        public string SingleSMSEngineBlacklist(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            Support.SorenaSms.SingleSMSEngineBlacklistRequest inValue = new Support.SorenaSms.SingleSMSEngineBlacklistRequest();
            inValue.Body = new Support.SorenaSms.SingleSMSEngineBlacklistRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            Support.SorenaSms.SingleSMSEngineBlacklistResponse retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).SingleSMSEngineBlacklist(inValue);
            return retVal.Body.SingleSMSEngineBlacklistResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineBlacklistResponse> Support.SorenaSms.sornaserviceSoap.SingleSMSEngineBlacklistAsync(Support.SorenaSms.SingleSMSEngineBlacklistRequest request) {
            return base.Channel.SingleSMSEngineBlacklistAsync(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngineBlacklistResponse> SingleSMSEngineBlacklistAsync(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            Support.SorenaSms.SingleSMSEngineBlacklistRequest inValue = new Support.SorenaSms.SingleSMSEngineBlacklistRequest();
            inValue.Body = new Support.SorenaSms.SingleSMSEngineBlacklistRequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).SingleSMSEngineBlacklistAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Support.SorenaSms.SingleSMSEngine021Response Support.SorenaSms.sornaserviceSoap.SingleSMSEngine021(Support.SorenaSms.SingleSMSEngine021Request request) {
            return base.Channel.SingleSMSEngine021(request);
        }
        
        public string SingleSMSEngine021(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            Support.SorenaSms.SingleSMSEngine021Request inValue = new Support.SorenaSms.SingleSMSEngine021Request();
            inValue.Body = new Support.SorenaSms.SingleSMSEngine021RequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            Support.SorenaSms.SingleSMSEngine021Response retVal = ((Support.SorenaSms.sornaserviceSoap)(this)).SingleSMSEngine021(inValue);
            return retVal.Body.SingleSMSEngine021Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngine021Response> Support.SorenaSms.sornaserviceSoap.SingleSMSEngine021Async(Support.SorenaSms.SingleSMSEngine021Request request) {
            return base.Channel.SingleSMSEngine021Async(request);
        }
        
        public System.Threading.Tasks.Task<Support.SorenaSms.SingleSMSEngine021Response> SingleSMSEngine021Async(int PortalCode, string UserName, string PassWord, string Mobile, string Message) {
            Support.SorenaSms.SingleSMSEngine021Request inValue = new Support.SorenaSms.SingleSMSEngine021Request();
            inValue.Body = new Support.SorenaSms.SingleSMSEngine021RequestBody();
            inValue.Body.PortalCode = PortalCode;
            inValue.Body.UserName = UserName;
            inValue.Body.PassWord = PassWord;
            inValue.Body.Mobile = Mobile;
            inValue.Body.Message = Message;
            return ((Support.SorenaSms.sornaserviceSoap)(this)).SingleSMSEngine021Async(inValue);
        }
    }
}
